"use strict";var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},notReady:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}}};
sjcl.cipher.aes=function(a){this.s[0][0][0]||this.J();var b,c,e,d,f=this.s[0][4],g=this.s[1];b=a.length;var h=1;if(4!==b&&6!==b&&8!==b)throw new sjcl.exception.invalid("invalid aes key size");this.b=[e=a.slice(0),d=[]];for(a=b;a<4*b+28;a++){c=e[a-1];if(0===a%b||8===b&&4===a%b)c=f[c>>>24]<<24^f[c>>16&255]<<16^f[c>>8&255]<<8^f[c&255],0===a%b&&(c=c<<8^c>>>24^h<<24,h=h<<1^283*(h>>7));e[a]=e[a-b]^c}for(b=0;a;b++,a--)c=e[b&3?a:a-4],d[b]=4>=a||4>b?c:g[0][f[c>>>24]]^g[1][f[c>>16&255]]^g[2][f[c>>8&255]]^g[3][f[c&
255]]};
sjcl.cipher.aes.prototype={encrypt:function(a){return r(this,a,0)},decrypt:function(a){return r(this,a,1)},s:[[[],[],[],[],[]],[[],[],[],[],[]]],J:function(){var a=this.s[0],b=this.s[1],c=a[4],e=b[4],d,f,g,h=[],k=[],n,m,l,p;for(d=0;0x100>d;d++)k[(h[d]=d<<1^283*(d>>7))^d]=d;for(f=g=0;!c[f];f^=n||1,g=k[g]||1)for(l=g^g<<1^g<<2^g<<3^g<<4,l=l>>8^l&255^99,c[f]=l,e[l]=f,m=h[d=h[n=h[f]]],p=0x1010101*m^0x10001*d^0x101*n^0x1010100*f,m=0x101*h[l]^0x1010100*l,d=0;4>d;d++)a[d][f]=m=m<<24^m>>>8,b[d][l]=p=p<<24^p>>>8;for(d=
0;5>d;d++)a[d]=a[d].slice(0),b[d]=b[d].slice(0)}};
function r(a,b,c){if(4!==b.length)throw new sjcl.exception.invalid("invalid aes block size");var e=a.b[c],d=b[0]^e[0],f=b[c?3:1]^e[1],g=b[2]^e[2];b=b[c?1:3]^e[3];var h,k,n,m=e.length/4-2,l,p=4,q=[0,0,0,0];h=a.s[c];a=h[0];var u=h[1],v=h[2],w=h[3],x=h[4];for(l=0;l<m;l++)h=a[d>>>24]^u[f>>16&255]^v[g>>8&255]^w[b&255]^e[p],k=a[f>>>24]^u[g>>16&255]^v[b>>8&255]^w[d&255]^e[p+1],n=a[g>>>24]^u[b>>16&255]^v[d>>8&255]^w[f&255]^e[p+2],b=a[b>>>24]^u[d>>16&255]^v[f>>8&255]^w[g&255]^e[p+3],p+=4,d=h,f=k,g=n;for(l=
0;4>l;l++)q[c?3&-l:l]=x[d>>>24]<<24^x[f>>16&255]<<16^x[g>>8&255]<<8^x[b&255]^e[p++],h=d,d=f,f=g,g=b,b=h;return q}
sjcl.bitArray={bitSlice:function(a,b,c){a=sjcl.bitArray.S(a.slice(b/32),32-(b&31)).slice(1);return void 0===c?a:sjcl.bitArray.clamp(a,c-b)},extract:function(a,b,c){var e=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-e^a[b/32+1|0]>>>e:a[b/32|0]>>>e)&(1<<c)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var c=a[a.length-1],e=sjcl.bitArray.getPartial(c);return 32===e?a.concat(b):sjcl.bitArray.S(b,e,c|0,a.slice(0,a.length-1))},bitLength:function(a){var b=a.length;return 0===
b?0:32*(b-1)+sjcl.bitArray.getPartial(a[b-1])},clamp:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var c=a.length;b=b&31;0<c&&b&&(a[c-1]=sjcl.bitArray.partial(b,a[c-1]&2147483648>>b-1,1));return a},partial:function(a,b,c){return 32===a?b:(c?b|0:b<<32-a)+0x10000000000*a},getPartial:function(a){return Math.round(a/0x10000000000)||32},equal:function(a,b){if(sjcl.bitArray.bitLength(a)!==sjcl.bitArray.bitLength(b))return!1;var c=0,e;for(e=0;e<a.length;e++)c|=a[e]^b[e];return 0===
c},S:function(a,b,c,e){var d;d=0;for(void 0===e&&(e=[]);32<=b;b-=32)e.push(c),c=0;if(0===b)return e.concat(a);for(d=0;d<a.length;d++)e.push(c|a[d]>>>b),c=a[d]<<32-b;d=a.length?a[a.length-1]:0;a=sjcl.bitArray.getPartial(d);e.push(sjcl.bitArray.partial(b+a&31,32<b+a?c:e.pop(),1));return e},da:function(a,b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]},byteswapM:function(a){var b,c;for(b=0;b<a.length;++b)c=a[b],a[b]=c>>>24|c>>>8&0xff00|(c&0xff00)<<8|c<<24;return a}};
sjcl.codec.utf8String={fromBits:function(a){var b="",c=sjcl.bitArray.bitLength(a),e,d;for(e=0;e<c/8;e++)0===(e&3)&&(d=a[e/4]),b+=String.fromCharCode(d>>>8>>>8>>>8),d<<=8;return decodeURIComponent(escape(b))},toBits:function(a){a=unescape(encodeURIComponent(a));var b=[],c,e=0;for(c=0;c<a.length;c++)e=e<<8|a.charCodeAt(c),3===(c&3)&&(b.push(e),e=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),e));return b}};
sjcl.codec.base64={N:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",fromBits:function(a,b,c){var e="",d=0,f=sjcl.codec.base64.N,g=0,h=sjcl.bitArray.bitLength(a);c&&(f=f.substr(0,62)+"-_");for(c=0;6*e.length<h;)e+=f.charAt((g^a[c]>>>d)>>>26),6>d?(g=a[c]<<6-d,d+=26,c++):(g<<=6,d-=6);for(;e.length&3&&!b;)e+="=";return e},toBits:function(a,b){a=a.replace(/\s|=/g,"");var c=[],e,d=0,f=sjcl.codec.base64.N,g=0,h;b&&(f=f.substr(0,62)+"-_");for(e=0;e<a.length;e++){h=f.indexOf(a.charAt(e));
if(0>h)throw new sjcl.exception.invalid("this isn't base64!");26<d?(d-=26,c.push(g^h>>>d),g=h<<32-d):(d+=6,g^=h<<32-d)}d&56&&c.push(sjcl.bitArray.partial(d&56,g,1));return c}};sjcl.codec.base64url={fromBits:function(a){return sjcl.codec.base64.fromBits(a,1,1)},toBits:function(a){return sjcl.codec.base64.toBits(a,1)}};sjcl.hash.sha256=function(a){this.b[0]||this.J();a?(this.g=a.g.slice(0),this.f=a.f.slice(0),this.c=a.c):this.reset()};sjcl.hash.sha256.hash=function(a){return(new sjcl.hash.sha256).update(a).finalize()};
sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this.g=this.A.slice(0);this.f=[];this.c=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.f=sjcl.bitArray.concat(this.f,a);b=this.c;a=this.c=b+sjcl.bitArray.bitLength(a);if(0x1fffffffffffff<a)throw new sjcl.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var e=new Uint32Array(c),d=0;for(b=512+b-(512+b&0x1ff);b<=a;b+=512)this.j(e.subarray(16*d,
16*(d+1))),d+=1;c.splice(0,16*d)}else for(b=512+b-(512+b&0x1ff);b<=a;b+=512)this.j(c.splice(0,16));return this},finalize:function(){var a,b=this.f,c=this.g,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this.c/0x100000000));for(b.push(this.c|0);b.length;)this.j(b.splice(0,16));this.reset();return c},A:[],b:[],J:function(){function a(a){return 0x100000000*(a-Math.floor(a))|0}for(var b=0,c=2,e,d;64>b;c++){d=!0;for(e=2;e*e<=c;e++)if(0===c%e){d=
!1;break}d&&(8>b&&(this.A[b]=a(Math.pow(c,.5))),this.b[b]=a(Math.pow(c,1/3)),b++)}},j:function(a){var b,c,e,d=this.g,f=this.b,g=d[0],h=d[1],k=d[2],n=d[3],m=d[4],l=d[5],p=d[6],q=d[7];for(b=0;64>b;b++)16>b?c=a[b]:(c=a[b+1&15],e=a[b+14&15],c=a[b&15]=(c>>>7^c>>>18^c>>>3^c<<25^c<<14)+(e>>>17^e>>>19^e>>>10^e<<15^e<<13)+a[b&15]+a[b+9&15]|0),c=c+q+(m>>>6^m>>>11^m>>>25^m<<26^m<<21^m<<7)+(p^m&(l^p))+f[b],q=p,p=l,l=m,m=n+c|0,n=k,k=h,h=g,g=c+(h&k^n&(h^k))+(h>>>2^h>>>13^h>>>22^h<<30^h<<19^h<<10)|0;d[0]=d[0]+g|
0;d[1]=d[1]+h|0;d[2]=d[2]+k|0;d[3]=d[3]+n|0;d[4]=d[4]+m|0;d[5]=d[5]+l|0;d[6]=d[6]+p|0;d[7]=d[7]+q|0}};sjcl.hash.sha1=function(a){a?(this.g=a.g.slice(0),this.f=a.f.slice(0),this.c=a.c):this.reset()};sjcl.hash.sha1.hash=function(a){return(new sjcl.hash.sha1).update(a).finalize()};
sjcl.hash.sha1.prototype={blockSize:512,reset:function(){this.g=this.A.slice(0);this.f=[];this.c=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.f=sjcl.bitArray.concat(this.f,a);b=this.c;a=this.c=b+sjcl.bitArray.bitLength(a);if(0x1fffffffffffff<a)throw new sjcl.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var e=new Uint32Array(c),d=0;for(b=this.blockSize+b-(this.blockSize+b&this.blockSize-1);b<=
a;b+=this.blockSize)this.j(e.subarray(16*d,16*(d+1))),d+=1;c.splice(0,16*d)}else for(b=this.blockSize+b-(this.blockSize+b&this.blockSize-1);b<=a;b+=this.blockSize)this.j(c.splice(0,16));return this},finalize:function(){var a,b=this.f,c=this.g,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this.c/0x100000000));for(b.push(this.c|0);b.length;)this.j(b.splice(0,16));this.reset();return c},A:[1732584193,4023233417,2562383102,271733878,3285377520],
b:[1518500249,1859775393,2400959708,3395469782],j:function(a){var b,c,e,d,f,g,h=this.g,k;if("undefined"!==typeof Uint32Array)for(k=Array(80),c=0;16>c;c++)k[c]=a[c];else k=a;c=h[0];e=h[1];d=h[2];f=h[3];g=h[4];for(a=0;79>=a;a++)16<=a&&(b=k[a-3]^k[a-8]^k[a-14]^k[a-16],k[a]=b<<1|b>>>31),b=19>=a?e&d|~e&f:39>=a?e^d^f:59>=a?e&d|e&f|d&f:79>=a?e^d^f:void 0,b=(c<<5|c>>>27)+b+g+k[a]+this.b[Math.floor(a/20)]|0,g=f,f=d,d=e<<30|e>>>2,e=c,c=b;h[0]=h[0]+c|0;h[1]=h[1]+e|0;h[2]=h[2]+d|0;h[3]=h[3]+f|0;h[4]=h[4]+g|0}};
sjcl.misc.hmac=function(a,b){this.P=b=b||sjcl.hash.sha256;var c=[[],[]],e,d=b.prototype.blockSize/32;this.v=[new b,new b];a.length>d&&(a=b.hash(a));for(e=0;e<d;e++)c[0][e]=a[e]^909522486,c[1][e]=a[e]^1549556828;this.v[0].update(c[0]);this.v[1].update(c[1]);this.L=new b(this.v[0])};sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(a){if(this.T)throw new sjcl.exception.invalid("encrypt on already updated hmac called!");this.update(a);return this.digest(a)};
sjcl.misc.hmac.prototype.reset=function(){this.L=new this.P(this.v[0]);this.T=!1};sjcl.misc.hmac.prototype.update=function(a){this.T=!0;this.L.update(a)};sjcl.misc.hmac.prototype.digest=function(){var a=this.L.finalize(),a=(new this.P(this.v[1])).update(a).finalize();this.reset();return a};
sjcl.misc.pbkdf2=function(a,b,c,e,d){c=c||1E4;if(0>e||0>c)throw new sjcl.exception.invalid("invalid params to pbkdf2");"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));d=d||sjcl.misc.hmac;a=new d(a);var f,g,h,k,n=[],m=sjcl.bitArray;for(k=1;32*n.length<(e||1);k++){d=f=a.encrypt(m.concat(b,[k]));for(g=1;g<c;g++)for(f=a.encrypt(f),h=0;h<f.length;h++)d[h]^=f[h];n=n.concat(d)}e&&(n=m.clamp(n,e));return n};
sjcl.prng=function(a){this.h=[new sjcl.hash.sha256];this.m=[0];this.K=0;this.B={};this.I=0;this.O={};this.R=this.i=this.o=this.Z=0;this.b=[0,0,0,0,0,0,0,0];this.l=[0,0,0,0];this.G=void 0;this.H=a;this.w=!1;this.F={progress:{},seeded:{}};this.u=this.Y=0;this.C=1;this.D=2;this.V=0x10000;this.M=[0,48,64,96,128,192,0x100,384,512,768,1024];this.W=3E4;this.U=80};
sjcl.prng.prototype={randomWords:function(a,b){var c=[],e;e=this.isReady(b);var d;if(e===this.u)throw new sjcl.exception.notReady("generator isn't seeded");if(e&this.D){e=!(e&this.C);d=[];var f=0,g;this.R=d[0]=(new Date).valueOf()+this.W;for(g=0;16>g;g++)d.push(0x100000000*Math.random()|0);for(g=0;g<this.h.length&&(d=d.concat(this.h[g].finalize()),f+=this.m[g],this.m[g]=0,e||!(this.K&1<<g));g++);this.K>=1<<this.h.length&&(this.h.push(new sjcl.hash.sha256),this.m.push(0));this.i-=f;f>this.o&&(this.o=
f);this.K++;this.b=sjcl.hash.sha256.hash(this.b.concat(d));this.G=new sjcl.cipher.aes(this.b);for(e=0;4>e&&(this.l[e]=this.l[e]+1|0,!this.l[e]);e++);}for(e=0;e<a;e+=4)0===(e+1)%this.V&&t(this),d=y(this),c.push(d[0],d[1],d[2],d[3]);t(this);return c.slice(0,a)},setDefaultParanoia:function(a,b){if(0===a&&"Setting paranoia=0 will ruin your security; use it only for testing"!==b)throw new sjcl.exception.invalid("Setting paranoia=0 will ruin your security; use it only for testing");this.H=a},addEntropy:function(a,
b,c){c=c||"user";var e,d,f=(new Date).valueOf(),g=this.B[c],h=this.isReady(),k=0;e=this.O[c];void 0===e&&(e=this.O[c]=this.Z++);void 0===g&&(g=this.B[c]=0);this.B[c]=(this.B[c]+1)%this.h.length;switch(typeof a){case "number":void 0===b&&(b=1);this.h[g].update([e,this.I++,1,b,f,1,a|0]);break;case "object":c=Object.prototype.toString.call(a);if("[object Uint32Array]"===c){d=[];for(c=0;c<a.length;c++)d.push(a[c]);a=d}else for("[object Array]"!==c&&(k=1),c=0;c<a.length&&!k;c++)"number"!==typeof a[c]&&
(k=1);if(!k){if(void 0===b)for(c=b=0;c<a.length;c++)for(d=a[c];0<d;)b++,d=d>>>1;this.h[g].update([e,this.I++,2,b,f,a.length].concat(a))}break;case "string":void 0===b&&(b=a.length);this.h[g].update([e,this.I++,3,b,f,a.length]);this.h[g].update(a);break;default:k=1}if(k)throw new sjcl.exception.bug("random: addEntropy only supports number, array of numbers or string");this.m[g]+=b;this.i+=b;h===this.u&&(this.isReady()!==this.u&&z("seeded",Math.max(this.o,this.i)),z("progress",this.getProgress()))},
isReady:function(a){a=this.M[void 0!==a?a:this.H];return this.o&&this.o>=a?this.m[0]>this.U&&(new Date).valueOf()>this.R?this.D|this.C:this.C:this.i>=a?this.D|this.u:this.u},getProgress:function(a){a=this.M[a?a:this.H];return this.o>=a?1:this.i>a?1:this.i/a},startCollectors:function(){if(!this.w){this.a={loadTimeCollector:A(this,this.aa),mouseCollector:A(this,this.ba),keyboardCollector:A(this,this.$),accelerometerCollector:A(this,this.X),touchCollector:A(this,this.ca)};if(window.addEventListener)window.addEventListener("load",
this.a.loadTimeCollector,!1),window.addEventListener("mousemove",this.a.mouseCollector,!1),window.addEventListener("keypress",this.a.keyboardCollector,!1),window.addEventListener("devicemotion",this.a.accelerometerCollector,!1),window.addEventListener("touchmove",this.a.touchCollector,!1);else if(document.attachEvent)document.attachEvent("onload",this.a.loadTimeCollector),document.attachEvent("onmousemove",this.a.mouseCollector),document.attachEvent("keypress",this.a.keyboardCollector);else throw new sjcl.exception.bug("can't attach event");
this.w=!0}},stopCollectors:function(){this.w&&(window.removeEventListener?(window.removeEventListener("load",this.a.loadTimeCollector,!1),window.removeEventListener("mousemove",this.a.mouseCollector,!1),window.removeEventListener("keypress",this.a.keyboardCollector,!1),window.removeEventListener("devicemotion",this.a.accelerometerCollector,!1),window.removeEventListener("touchmove",this.a.touchCollector,!1)):document.detachEvent&&(document.detachEvent("onload",this.a.loadTimeCollector),document.detachEvent("onmousemove",
this.a.mouseCollector),document.detachEvent("keypress",this.a.keyboardCollector)),this.w=!1)},addEventListener:function(a,b){this.F[a][this.Y++]=b},removeEventListener:function(a,b){var c,e,d=this.F[a],f=[];for(e in d)d.hasOwnProperty(e)&&d[e]===b&&f.push(e);for(c=0;c<f.length;c++)e=f[c],delete d[e]},$:function(){B(this,1)},ba:function(a){var b,c;try{b=a.x||a.clientX||a.offsetX||0,c=a.y||a.clientY||a.offsetY||0}catch(e){c=b=0}0!=b&&0!=c&&this.addEntropy([b,c],2,"mouse");B(this,0)},ca:function(a){a=
a.touches[0]||a.changedTouches[0];this.addEntropy([a.pageX||a.clientX,a.pageY||a.clientY],1,"touch");B(this,0)},aa:function(){B(this,2)},X:function(a){a=a.accelerationIncludingGravity.x||a.accelerationIncludingGravity.y||a.accelerationIncludingGravity.z;if(window.orientation){var b=window.orientation;"number"===typeof b&&this.addEntropy(b,1,"accelerometer")}a&&this.addEntropy(a,2,"accelerometer");B(this,0)}};
function z(a,b){var c,e=sjcl.random.F[a],d=[];for(c in e)e.hasOwnProperty(c)&&d.push(e[c]);for(c=0;c<d.length;c++)d[c](b)}function B(a,b){"undefined"!==typeof window&&window.performance&&"function"===typeof window.performance.now?a.addEntropy(window.performance.now(),b,"loadtime"):a.addEntropy((new Date).valueOf(),b,"loadtime")}function t(a){a.b=y(a).concat(y(a));a.G=new sjcl.cipher.aes(a.b)}function y(a){for(var b=0;4>b&&(a.l[b]=a.l[b]+1|0,!a.l[b]);b++);return a.G.encrypt(a.l)}
function A(a,b){return function(){b.apply(a,arguments)}}sjcl.random=new sjcl.prng(6);
a:try{var C,D,E,F;if(F="undefined"!==typeof module&&module.exports){var G;try{G=require("crypto")}catch(a){G=null}F=D=G}if(F&&D.randomBytes)C=D.randomBytes(128),C=new Uint32Array((new Uint8Array(C)).buffer),sjcl.random.addEntropy(C,1024,"crypto['randomBytes']");else if("undefined"!==typeof window&&"undefined"!==typeof Uint32Array){E=new Uint32Array(32);if(window.crypto&&window.crypto.getRandomValues)window.crypto.getRandomValues(E);else if(window.msCrypto&&window.msCrypto.getRandomValues)window.msCrypto.getRandomValues(E);
else break a;sjcl.random.addEntropy(E,1024,"crypto['getRandomValues']")}}catch(a){"undefined"!==typeof window&&window.console&&(console.log("There was an error collecting entropy from the browser:"),console.log(a))}"undefined"!==typeof module&&module.exports&&(module.exports=sjcl);"function"===typeof define&&define([],function(){return sjcl});
